import { NextRequest, NextResponse } from "next/server"
import jwt from "jsonwebtoken"
import { prisma } from "@/app/lib/prisma"

interface AuthJwtPayload {
  id: string
  email: string
  role: string
  department?: string
  iat?: number
  exp?: number
}

/**
 * Get JWT secret
 */
function getJwtSecret(): string {
  const secret = process.env.JWT_SECRET

  if (!secret) {
    throw new Error("JWT_SECRET is not configured in .env")
  }

  return secret
}

/**
 * Read and verify JWT from Authorization header
 */
function getUserFromRequest(
  request: NextRequest
): AuthJwtPayload | null {
  try {
    const authHeader =
      request.headers.get("authorization")

    if (!authHeader) {
      console.log(
        "❌ Authorization header missing"
      )

      return null
    }

    if (!authHeader.startsWith("Bearer ")) {
      console.log(
        "❌ Authorization header is not Bearer"
      )

      return null
    }

    const token = authHeader.substring(7)

    if (!token) {
      console.log("❌ JWT token is empty")

      return null
    }

    /**
     * jwt.verify() has multiple TypeScript overloads.
     *
     * We first verify the token and then safely
     * validate the payload ourselves.
     */
    const decoded = jwt.verify(
      token,
      getJwtSecret()
    ) as unknown

    if (
      typeof decoded !== "object" ||
      decoded === null
    ) {
      console.log("❌ Invalid JWT payload")

      return null
    }

    const payload =
      decoded as Record<string, unknown>

    /**
     * Make sure our JWT contains the
     * fields generated by the login APIs.
     */
    if (
      typeof payload.id !== "string" ||
      typeof payload.email !== "string" ||
      typeof payload.role !== "string"
    ) {
      console.log(
        "❌ JWT missing required fields:",
        payload
      )

      return null
    }

    return {
      id: payload.id,
      email: payload.email,
      role: payload.role,
      department:
        typeof payload.department === "string"
          ? payload.department
          : undefined,
      iat:
        typeof payload.iat === "number"
          ? payload.iat
          : undefined,
      exp:
        typeof payload.exp === "number"
          ? payload.exp
          : undefined,
    }
  } catch (error) {
    console.error(
      "❌ JWT verification failed:",
      error
    )

    return null
  }
}

/* =========================================================
   GET /api/leads/transfer
   =========================================================

   ADMIN:
   → Can see all employees

   MANAGER:
   → Can see employees from their department

   EMPLOYEE:
   → Not allowed
*/
export async function GET(
  request: NextRequest
) {
  try {
    const user =
      getUserFromRequest(request)

    if (!user) {
      return NextResponse.json(
        {
          error: "Unauthorized",
          message:
            "Invalid or missing authentication token",
        },
        {
          status: 401,
        }
      )
    }

    const role = user.role
      .trim()
      .toLowerCase()

    console.log(
      "===================================="
    )
    console.log(
      "TRANSFER API USER"
    )
    console.log("ID:", user.id)
    console.log("Email:", user.email)
    console.log("Role:", user.role)
    console.log(
      "Department:",
      user.department
    )
    console.log(
      "===================================="
    )

    /**
     * Only ADMIN and MANAGER
     */
    if (
      role !== "admin" &&
      role !== "manager"
    ) {
      return NextResponse.json(
        {
          error:
            "You are not allowed to transfer leads",
        },
        {
          status: 403,
        }
      )
    }

    /**
     * ADMIN
     *
     * Admin can transfer to any employee.
     */
    if (role === "admin") {
      const employees =
        await prisma.employee.findMany({
          orderBy: {
            name: "asc",
          },

          select: {
            id: true,
            name: true,
            email: true,
            departmentId: true,
          },
        })

      return NextResponse.json({
        employees,
      })
    }

    /**
     * MANAGER
     *
     * Manager can only transfer to
     * employees in their department.
     */
    if (role === "manager") {
      const manager =
        await prisma.manager.findUnique({
          where: {
            id: user.id,
          },

          select: {
            id: true,
            departmentId: true,
          },
        })

      if (!manager) {
        return NextResponse.json(
          {
            error:
              "Manager account not found",
          },
          {
            status: 404,
          }
        )
      }

      const employees =
        await prisma.employee.findMany({
          where: {
            departmentId:
              manager.departmentId,
          },

          orderBy: {
            name: "asc",
          },

          select: {
            id: true,
            name: true,
            email: true,
            departmentId: true,
          },
        })

      return NextResponse.json({
        employees,
      })
    }

    return NextResponse.json(
      {
        error: "Invalid role",
      },
      {
        status: 403,
      }
    )
  } catch (error) {
    console.error(
      "❌ GET /api/leads/transfer error:",
      error
    )

    return NextResponse.json(
      {
        error: "Failed to load employees",
      },
      {
        status: 500,
      }
    )
  }
}

/* =========================================================
   POST /api/leads/transfer
   =========================================================

   ADMIN:
   → Can transfer any lead

   MANAGER:
   → Can transfer leads within their department

   EMPLOYEE:
   → Not allowed
*/
export async function POST(
  request: NextRequest
) {
  try {
    const user =
      getUserFromRequest(request)

    if (!user) {
      return NextResponse.json(
        {
          error: "Unauthorized",
          message:
            "Invalid or missing authentication token",
        },
        {
          status: 401,
        }
      )
    }

    const role = user.role
      .trim()
      .toLowerCase()

    console.log(
      "===================================="
    )
    console.log(
      "TRANSFER LEAD REQUEST"
    )
    console.log("User ID:", user.id)
    console.log("Email:", user.email)
    console.log("Role:", user.role)
    console.log(
      "===================================="
    )

    /**
     * Only ADMIN and MANAGER
     */
    if (
      role !== "admin" &&
      role !== "manager"
    ) {
      return NextResponse.json(
        {
          error:
            "You are not allowed to transfer leads",
        },
        {
          status: 403,
        }
      )
    }

    /**
     * Request body
     */
    const body = await request.json()

    const {
      leadId,
      employeeId,
    } = body

    if (!leadId || !employeeId) {
      return NextResponse.json(
        {
          error:
            "Lead ID and employee ID are required",
        },
        {
          status: 400,
        }
      )
    }

    /**
     * Find lead
     */
    const lead =
      await prisma.lead.findUnique({
        where: {
          id: leadId,
        },

        select: {
          id: true,
          name: true,
          employeeId: true,
          status: true,
        },
      })

    if (!lead) {
      return NextResponse.json(
        {
          error: "Lead not found",
        },
        {
          status: 404,
        }
      )
    }

    /**
     * Find target employee
     */
    const targetEmployee =
      await prisma.employee.findUnique({
        where: {
          id: employeeId,
        },

        select: {
          id: true,
          name: true,
          email: true,
          departmentId: true,
        },
      })

    if (!targetEmployee) {
      return NextResponse.json(
        {
          error:
            "Target employee not found",
        },
        {
          status: 404,
        }
      )
    }

    /**
     * Prevent transferring to
     * the same employee
     */
    if (
      lead.employeeId === employeeId
    ) {
      return NextResponse.json(
        {
          error:
            "Lead is already assigned to this employee",
        },
        {
          status: 400,
        }
      )
    }

    /**
     * =====================================================
     * MANAGER RESTRICTIONS
     * =====================================================
     */
    if (role === "manager") {
      /**
       * Find manager
       */
      const manager =
        await prisma.manager.findUnique({
          where: {
            id: user.id,
          },

          select: {
            id: true,
            departmentId: true,
          },
        })

      if (!manager) {
        return NextResponse.json(
          {
            error:
              "Manager account not found",
          },
          {
            status: 404,
          }
        )
      }

      /**
       * Find current lead owner
       */
      const sourceEmployee =
        await prisma.employee.findUnique({
          where: {
            id: lead.employeeId,
          },

          select: {
            id: true,
            name: true,
            departmentId: true,
          },
        })

      if (!sourceEmployee) {
        return NextResponse.json(
          {
            error:
              "Current lead owner not found",
          },
          {
            status: 404,
          }
        )
      }

      /**
       * Lead must belong to
       * manager's department.
       */
      if (
        sourceEmployee.departmentId !==
        manager.departmentId
      ) {
        return NextResponse.json(
          {
            error:
              "You can only transfer leads from your department",
          },
          {
            status: 403,
          }
        )
      }

      /**
       * Target employee must belong
       * to manager's department.
       */
      if (
        targetEmployee.departmentId !==
        manager.departmentId
      ) {
        return NextResponse.json(
          {
            error:
              "You can only transfer leads to employees in your department",
          },
          {
            status: 403,
          }
        )
      }
    }

    /**
     * =====================================================
     * TRANSFER LEAD
     * =====================================================
     */
    const updatedLead =
      await prisma.lead.update({
        where: {
          id: leadId,
        },

        data: {
          employeeId: employeeId,
        },

        include: {
          employee: {
            select: {
              id: true,
              name: true,
              email: true,
            },
          },
        },
      })

    console.log(
      `✅ Lead ${leadId} transferred from ${lead.employeeId} to ${employeeId}`
    )

    return NextResponse.json({
      success: true,

      message:
        "Lead transferred successfully",

      lead: updatedLead,
    })
  } catch (error) {
    console.error(
      "❌ POST /api/leads/transfer error:",
      error
    )

    return NextResponse.json(
      {
        error:
          "Failed to transfer lead",
      },
      {
        status: 500,
      }
    )
  }
}